from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import TransactionInitializeSessionEvent


class TransactionInitializeSession(BaseModel):
    event: Optional[
        Annotated[
            Union[
                "TransactionInitializeSessionEventEvent",
                "TransactionInitializeSessionEventTransactionInitializeSession",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class TransactionInitializeSessionEventEvent(BaseModel):
    typename__: Literal[
        "AccountChangeEmailRequested",
        "AccountConfirmationRequested",
        "AccountConfirmed",
        "AccountDeleteRequested",
        "AccountDeleted",
        "AccountEmailChanged",
        "AccountSetPasswordRequested",
        "AddressCreated",
        "AddressDeleted",
        "AddressUpdated",
        "AppDeleted",
        "AppInstalled",
        "AppStatusChanged",
        "AppUpdated",
        "AttributeCreated",
        "AttributeDeleted",
        "AttributeUpdated",
        "AttributeValueCreated",
        "AttributeValueDeleted",
        "AttributeValueUpdated",
        "CalculateTaxes",
        "CategoryCreated",
        "CategoryDeleted",
        "CategoryUpdated",
        "ChannelCreated",
        "ChannelDeleted",
        "ChannelMetadataUpdated",
        "ChannelStatusChanged",
        "ChannelUpdated",
        "CheckoutCreated",
        "CheckoutFilterShippingMethods",
        "CheckoutFullyPaid",
        "CheckoutMetadataUpdated",
        "CheckoutUpdated",
        "CollectionCreated",
        "CollectionDeleted",
        "CollectionMetadataUpdated",
        "CollectionUpdated",
        "CustomerCreated",
        "CustomerMetadataUpdated",
        "CustomerUpdated",
        "DraftOrderCreated",
        "DraftOrderDeleted",
        "DraftOrderUpdated",
        "Event",
        "FulfillmentApproved",
        "FulfillmentCanceled",
        "FulfillmentCreated",
        "FulfillmentMetadataUpdated",
        "FulfillmentTrackingNumberUpdated",
        "GiftCardCreated",
        "GiftCardDeleted",
        "GiftCardExportCompleted",
        "GiftCardMetadataUpdated",
        "GiftCardSent",
        "GiftCardStatusChanged",
        "GiftCardUpdated",
        "InvoiceDeleted",
        "InvoiceRequested",
        "InvoiceSent",
        "ListStoredPaymentMethods",
        "MenuCreated",
        "MenuDeleted",
        "MenuItemCreated",
        "MenuItemDeleted",
        "MenuItemUpdated",
        "MenuUpdated",
        "OrderBulkCreated",
        "OrderCancelled",
        "OrderConfirmed",
        "OrderCreated",
        "OrderExpired",
        "OrderFilterShippingMethods",
        "OrderFulfilled",
        "OrderFullyPaid",
        "OrderFullyRefunded",
        "OrderMetadataUpdated",
        "OrderPaid",
        "OrderRefunded",
        "OrderUpdated",
        "PageCreated",
        "PageDeleted",
        "PageTypeCreated",
        "PageTypeDeleted",
        "PageTypeUpdated",
        "PageUpdated",
        "PaymentAuthorize",
        "PaymentCaptureEvent",
        "PaymentConfirmEvent",
        "PaymentGatewayInitializeSession",
        "PaymentGatewayInitializeTokenizationSession",
        "PaymentListGateways",
        "PaymentMethodInitializeTokenizationSession",
        "PaymentMethodProcessTokenizationSession",
        "PaymentProcessEvent",
        "PaymentRefundEvent",
        "PaymentVoidEvent",
        "PermissionGroupCreated",
        "PermissionGroupDeleted",
        "PermissionGroupUpdated",
        "ProductCreated",
        "ProductDeleted",
        "ProductExportCompleted",
        "ProductMediaCreated",
        "ProductMediaDeleted",
        "ProductMediaUpdated",
        "ProductMetadataUpdated",
        "ProductUpdated",
        "ProductVariantBackInStock",
        "ProductVariantCreated",
        "ProductVariantDeleted",
        "ProductVariantMetadataUpdated",
        "ProductVariantOutOfStock",
        "ProductVariantStockUpdated",
        "ProductVariantUpdated",
        "PromotionCreated",
        "PromotionDeleted",
        "PromotionEnded",
        "PromotionRuleCreated",
        "PromotionRuleDeleted",
        "PromotionRuleUpdated",
        "PromotionStarted",
        "PromotionUpdated",
        "SaleCreated",
        "SaleDeleted",
        "SaleToggle",
        "SaleUpdated",
        "ShippingListMethodsForCheckout",
        "ShippingPriceCreated",
        "ShippingPriceDeleted",
        "ShippingPriceUpdated",
        "ShippingZoneCreated",
        "ShippingZoneDeleted",
        "ShippingZoneMetadataUpdated",
        "ShippingZoneUpdated",
        "ShopMetadataUpdated",
        "StaffCreated",
        "StaffDeleted",
        "StaffSetPasswordRequested",
        "StaffUpdated",
        "StoredPaymentMethodDeleteRequested",
        "ThumbnailCreated",
        "TransactionCancelationRequested",
        "TransactionChargeRequested",
        "TransactionItemMetadataUpdated",
        "TransactionProcessSession",
        "TransactionRefundRequested",
        "TranslationCreated",
        "TranslationUpdated",
        "VoucherCodeExportCompleted",
        "VoucherCodesCreated",
        "VoucherCodesDeleted",
        "VoucherCreated",
        "VoucherDeleted",
        "VoucherMetadataUpdated",
        "VoucherUpdated",
        "WarehouseCreated",
        "WarehouseDeleted",
        "WarehouseMetadataUpdated",
        "WarehouseUpdated",
    ] = Field(alias="__typename")


class TransactionInitializeSessionEventTransactionInitializeSession(
    TransactionInitializeSessionEvent
):
    typename__: Literal["TransactionInitializeSession"] = Field(alias="__typename")


TransactionInitializeSession.model_rebuild()
